language: python
python:
  - '3.6'

before_install:
  - openssl aes-256-cbc -K $encrypted_d8f71da6b71d_key -iv $encrypted_d8f71da6b71d_iv -in google_auth.json.enc -out google_auth.json -d

install:
  - pip install pipenv
  - pipenv install

script:
  - pipenv run python run.py
